on: [push, pull_request]

name: Nix

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install nix
        uses: cachix/install-nix-action@v31
      - uses: actions/checkout@v6
      - name: Check formatting
        run: nix develop --command cargo fmt --check
      - name: Build
        run: nix develop --command cargo check --all-targets
      - name: Clippy
        run: nix develop --command cargo clippy --all-targets -- -Dwarnings
