on: [push, pull_request]

name: Nix

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install nix
        uses: cachix/install-nix-action@v31
      - uses: actions/checkout@v6
      - name: Run flake checks
        run: nix flake check . -L
